// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxF0Spd1L4OxgtSjxwG2g033CCz5zJw6k',
    appId: '1:371631480803:web:b06ffe330d5d9399408ad6',
    messagingSenderId: '371631480803',
    projectId: 'workout-master-78352',
    authDomain: 'workout-master-78352.firebaseapp.com',
    storageBucket: 'workout-master-78352.firebasestorage.app',
    measurementId: 'G-PQPMFY6DLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlAWe9p86Eex8dFTdxMs7UZ57at_yZi3w',
    appId: '1:371631480803:android:2b8402c4a887610a408ad6',
    messagingSenderId: '371631480803',
    projectId: 'workout-master-78352',
    storageBucket: 'workout-master-78352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuWUetOOMTdmrNyGXI4OkHuIESO-_nSZk',
    appId: '1:371631480803:ios:0703299c1defbb78408ad6',
    messagingSenderId: '371631480803',
    projectId: 'workout-master-78352',
    storageBucket: 'workout-master-78352.firebasestorage.app',
    iosBundleId: 'com.example.workoutMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuWUetOOMTdmrNyGXI4OkHuIESO-_nSZk',
    appId: '1:371631480803:ios:0703299c1defbb78408ad6',
    messagingSenderId: '371631480803',
    projectId: 'workout-master-78352',
    storageBucket: 'workout-master-78352.firebasestorage.app',
    iosBundleId: 'com.example.workoutMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxF0Spd1L4OxgtSjxwG2g033CCz5zJw6k',
    appId: '1:371631480803:web:41ba1f04a72da9f1408ad6',
    messagingSenderId: '371631480803',
    projectId: 'workout-master-78352',
    authDomain: 'workout-master-78352.firebaseapp.com',
    storageBucket: 'workout-master-78352.firebasestorage.app',
    measurementId: 'G-MZP2ZYD52C',
  );
}
